__title__ = "txMisTIC"
__description__ = "MisTIC: Missegmented Transcript Inference Correction for Improved Spatial Transcriptomics Analysis"
__version__ = "0.0.3"
__author__ = "Yuqiu Yang, Erica DePasquale, David Adeleke, Xiangfei Xie, Zeyu Lu, Michael D. Nelson, Guanghua Xiao, Xinlei Wang, Yunguan Wang"
__authoremail__ = "Yuqiu.Yang@utsouthwestern.edu, erica.depasquale@cchmc.org, david.adeleke@cchmc.org, xiangfei.xie@cchmc.org, zeyu.lu@uta.edu, michael.nelson3@uta.edu, guanghua.xiao@utsouthwestern.edu, xinlei.wang@uta.edu, yunguan.wang@cchmc.org"